######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 20 22:20:42 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myinputpanel.h options.h
FORMS += mainwindow.ui myinputpanelform.ui options.ui
SOURCES += main.cpp mainwindow.cpp myinputpanel.cpp options.cpp
